version: '3.1'

# docker compose up -d
services:
  mysql:
    image: 'mysql:8.0.35'
    container_name: spring-security-youtube-yumi
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=security
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - TZ=Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64